minjeong-kang33/Final_Mealki.s_Fridge

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/empManage.jsp, Mealki.s_Fridge/src/main/webapp/resources/employee/empMamagment.css
[2023.03.20] empMamage 페이지 전체적인 css변경 및 탭1 표 추가 및 크기 조절
=> [2023.03.20] empMamage 페이지 전체적인 css변경 및 탭1 표 추가 및 크기 조절

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/sidebar.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/stockManage.jsp
=> [2023.03.22]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp
=> [2023.03.23] insertStore 표 틀 생성

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp
insertStore 입력 혹은 submit 하는 경우 발주 개수 대비 입고 개수 초과 시 alert
=> [2023.03.24] insertStore 입력 혹은 submit 하는 경우 발주 개수 대비 입고 개수 초과 시 alert

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/findItem.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/findProduct.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
[2023.03.24]insertStore table컬럼 추가 및 입고수량 제한 추가
=> [2023.03.24]insertStore table컬럼 추가 및 입고수량 제한 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp
insertEmployee 파일 유첨 시 미리보기,
파일 유첨시 img만 받기처리
=> [2023.03.29]insertEmployee 파일 유첨 시 미리보기 외

Mealki.s_Fridge/src/main/resources/mappers/productionMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/quality/listForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/quality/writeForm.jsp, Mealki.s_Fridge/target/classes/mappers/productionMapper.xml
production mapper 수정
quality listform
writeform 추가
=> [23-03-29]

Mealki.s_Fridge/src/main/webapp/resources/wms/insertUnStore.css
=> [2023.03.30]unstore css추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
=> [2023.03.31] unstore 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
=> [2023.03.31]unstore 오류로 업로드

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.03.31]mapper수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoInsert.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoUpdate.jsp
작업지시서 등록 css 수정
작업지시서 상태 대기일시에만 수정 삭제 가능하도록 구현
=> [2023.03.31]

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
sto, unsto 날짜 디폴트값 수정 및 sto표 수정
=> [2023.04.01] sto, unsto 날짜 디폴트값 수정 및 sto표 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/resources/employee/insertEmployee.css, Mealki.s_Fridge/src/main/webapp/resources/wms/insertStore.css, Mealki.s_Fridge/src/main/webapp/resources/wms/insertUnStore.css
=> [2023.04.01] 사원등록, 입고관리, 출고관리 css 수정

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/storeDetail.jsp, Mealki.s_Fridge/src/main/webapp/resources/wms/detail.css, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.02] store 입고관리 상세 db와 jsp연결

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/storeDetail.jsp, Mealki.s_Fridge/src/main/webapp/resources/wms/detail.css
=> [2023.04.02] store Datail 인쇄기능 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/resources/wms/insertStore.css
=> [2023.04.03] insertStore 표 인쇄하기 기능 구현

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/main.jsp, Mealki.s_Fridge/src/main/webapp/resources/main/contractchart.js
[main.jsp contractchart.js 추가]
=> [2023.04.03]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/main.jsp, Mealki.s_Fridge/src/main/webapp/resources/main/fullcalendar-5.11.4/lib/main.css, Mealki.s_Fridge/src/main/webapp/resources/main/todoList.js, Mealki.s_Fridge/target/classes/mappers/stockMapper.xml
[2023.04.04] main화면에 회원별 to do list 기능 추가
=> [2023.04.04] main화면에 회원별 to do list 기능 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoInsert.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoUpdate.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/dmsg.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/list.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/umsg.jsp, Mealki.s_Fridge/src/main/webapp/resources/maincss/css/vertical-layout-light/style.css, Mealki.s_Fridge/src/main/webapp/resources/mps/workorder.css
modal 관련 전체 css 주석처리
작업지시서 상세 팝업 모달로 변경
=> [2023.04.04]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/updateEmployee.jsp
=> [2023.04.05] 휴직,복직,퇴직 버튼 클릭 후 부모창 새로고침

Mealki.s_Fridge/src/main/resources/mappers/unstoreMapper.xml, Mealki.s_Fridge/target/classes/mappers/unstoreMapper.xml
=> [2023.04.05] 출고 리스트 정렬 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/src/main/webapp/resources/wms/orderForm.css
[2023.04.05] 발주에서 품목선택보다 수량선택이 선행되지않도록 수정
=> [2023.04.05] 발주에서 품목선택보다 수량선택이 선행되지않도록 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
=> [2023.04.05] unstore 로딩 속도 개선

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/list.jsp
=> [2023.04.05]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/quality/writeclose.jsp
=> [23-04-05]

Mealki.s_Fridge/src/main/resources/mappers/workorderMapper.xml, Mealki.s_Fridge/target/classes/mappers/workorderMapper.xml
=> [2023.04.06]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/empManage.jsp
=> [2023.04.06] employeeManage css수정

Mealki.s_Fridge/src/main/resources/mappers/placeOrderMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/target/classes/mappers/placeOrderMapper.xml
[2023.04.06] 행삭제 버튼 추가, 재고 join sql문 수정
=> [2023.04.06] 행삭제 버튼 추가, 재고 join sql문 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/src/main/webapp/resources/wms/orderForm.css
=> [2023.04.06] 발주등록 자잘한 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp
=> [2023.04.06] 행추가 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/yellowPage.jsp
=> [2023.04.06]yellowPage ajax수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/yellowPage.jsp, Mealki.s_Fridge/src/main/webapp/resources/employee/yellowPage.css
=> [2023.04.06] yellowPageDetail 나누기 완료

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/yellowPage.jsp, Mealki.s_Fridge/src/main/webapp/resources/employee/yellowPage.css
=> [2023.04.06] yellowPage css적용

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/yellowPage.jsp, Mealki.s_Fridge/src/main/webapp/resources/employee/yellowPage.css
=> [2023.04.06] yellowPage 모달창 구현 완료

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/updateEmployee.jsp
insert, update Employee 정규표현식 추가
=> [2023.04.07] insert, update Employee 정규표현식 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/updateEmployee.jsp
updateEmployee select 구문 클린코드로 수정
=> [2023.04.07] updateEmployee select 구문 클린코드로 수정 

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp
=> [2023.04.07] insertStore 탭 문제로 인한 인쇄버튼 삭제

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findProducts.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/stockList.jsp
=> [2023.04.07] 재고 10미만 빨간표시

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/content.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingWrite.jsp, Mealki.s_Fridge/src/main/webapp/resources/business/contractList.css, Mealki.s_Fridge/src/main/webapp/resources/business/customerList.css, Mealki.s_Fridge/src/main/webapp/resources/business/shippingList.css
[2023.04.07]
contractList contractWrite shippingList shippingWrite css수정
=> [2023.04.07]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/production/writeclose.jsp
=> [23-04-07]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/unstoreDetail.jsp
insertStore 입고시 배열 alert 뜨던부분 수정
unstoreDetail 발주담당자 -> 작업지시 담당자로 수정
=> [2023.04.08] insertStore 입고시 배열 alert 뜨던부분 수정 외 

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/empManage.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
=> [2023.04.08] 메뉴 설명부분 (H6) 삭제

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/resources/mappers/unstoreMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/unstoreMapper.xml
=> [2023.04.08] 출고관리, 입고관리 리스트 정렬 변경

Mealki.s_Fridge/src/main/resources/mappers/employeeMapper.xml, Mealki.s_Fridge/target/classes/mappers/employeeMapper.xml
employeeMapper 사원조회시 쿼리문 오류 수정
=> [2023.04.08] employeeMapper 사원조회시 쿼리문 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/sidebar.jsp
=> [2023.04.08] 사원관리 - 인사부, 전산부만 메뉴확인 가능

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
[2023.04.08]출고, 입고 전산팀, 자재팀만 입고/출고 처리 가능하도록 수정
=> [2023.04.08]출고, 입고 전산팀, 자재팀만 입고/출고 처리 가능하도록 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/stockList.jsp
=> [2023.04.09] 재고, 발주 권한설정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/unstoreDetail.jsp
=> [2023.04.09] 출고상세 항목 오타 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/ContractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/ContractSearch.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoUpdate.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/dmsg.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/list.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/umsg.jsp
파비콘적용
수정, 삭제시 confirm 추가
작업지시서 등록, 수정, 삭제 부서별 권한 부여
=> [2023.04.09]

Mealki.s_Fridge/src/main/webapp/resources/wms/findProduct.css
=> [2023.04.09] findProduct.css추가

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.09] store 오류수정중

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.09] 입고 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/storeDetail.jsp
=> [2023.04.09] 입고 상세 오류 수정

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.09] 입고관리 리스트 오류 수정완료

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/updateEmployee.jsp, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
employee 경리부 -> R&D 로 변경
입고관리 리스트 쿼리수정
=> [2023.04.09]employee 경리부 -> R&D 로 변경 외

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.09] store 상세 오류로 매퍼 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp
=> [2023.04.10] 수주등록 날짜 기본값 지정

Mealki.s_Fridge/src/main/resources/mappers/workorderMapper.xml, Mealki.s_Fridge/target/classes/mappers/workorderMapper.xml
=> [2023.04.10] workorder 쿼리문 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mdm/item/itemlist.jsp
=> 품목리스트 수정시 품목코드 select박스 없애기, 기존 item_num의 P/I에 따른 품목유형 필터링, 기존 품목유형이 그대로

Mealki.s_Fridge/src/main/resources/mappers/shippingMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingList.jsp, Mealki.s_Fridge/src/main/webapp/resources/business/contractWrite.css, Mealki.s_Fridge/src/main/webapp/resources/business/shippingList.css, Mealki.s_Fridge/target/classes/mappers/shippingMapper.xml
=> [2023.04.10]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findEmp_num.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findProducts.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findWarehouse.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/findWarehouse.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/finditem_type.jsp
=> [2023.04.10] 파비콘 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingWrite.jsp, Mealki.s_Fridge/src/main/webapp/resources/shipping/shippingList.css, Mealki.s_Fridge/src/main/webapp/resources/shipping/shippingWrite.css
=> [2023.04.11]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mdm/item/itemlist.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mdm/recipe/recipeList.jsp, Mealki.s_Fridge/src/main/webapp/resources/main/calendar.js, Mealki.s_Fridge/src/main/webapp/resources/main/weather.js
소요량 입력칸 문자열 입력못하도록 입력제어,
품목리스트에서 중량, 납입단가, 출고단가 문자열 입력못하도록 제어
=> 소요량리스트에서 필수등록행 미입력시 저장안되게 alert 추가,

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/login.jsp
=> [2023.04.11] 사원등록 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/empManage.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/insertEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/updateEmployee.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/employee/yellowPage.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mdm/recipe/itemListPopup.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mdm/recipe/recipeList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/ContractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/ContractSearch.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoInsert.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/WoUpdate.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/workorder/list.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findEmp_num.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findProducts.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/findWarehouse.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/placeorder/orderForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/findWarehouse.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/finditem_type.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/stock/stockList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/findItem.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/findProduct.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/storeDetail.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/unstoreDetail.jsp
=> [2023.04.11] 파비콘 수정

Mealki.s_Fridge/src/main/resources/mappers/storeMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp, Mealki.s_Fridge/target/classes/mappers/storeMapper.xml
=> [2023.04.11] unstore, store 오류 수정

Mealki.s_Fridge/src/main/resources/mappers/chartMapper.xml, Mealki.s_Fridge/src/main/resources/mappers/qualityMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/sidebar.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/production/listForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/production/writeForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/quality/listForm.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/mps/quality/writeForm.jsp, Mealki.s_Fridge/src/main/webapp/resources/mps/productchart.js, Mealki.s_Fridge/src/main/webapp/resources/mps/production.css, Mealki.s_Fridge/target/classes/mappers/chartMapper.xml, Mealki.s_Fridge/target/classes/mappers/qualityMapper.xml
=> [23-04-11]

Mealki.s_Fridge/src/main/webapp/resources/main/calendar.js, Mealki.s_Fridge/src/main/webapp/resources/main/weather.js
=> [2023.04.11] api 코드 수정

Mealki.s_Fridge/src/main/resources/mappers/productionMapper.xml, Mealki.s_Fridge/src/main/resources/mappers/qualityMapper.xml, Mealki.s_Fridge/target/classes/mappers/productionMapper.xml, Mealki.s_Fridge/target/classes/mappers/qualityMapper.xml
=> [23-04-12]

Mealki.s_Fridge/src/main/resources/mappers/contractMapper.xml, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/content.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/update.jsp, Mealki.s_Fridge/src/main/webapp/resources/business/contractWrite.css, Mealki.s_Fridge/target/classes/mappers/contractMapper.xml
=> [2023.04.12] 수주 수정완료

Mealki.s_Fridge/src/main/webapp/resources/business/contractUpdate.css
=> [2023.04.12] 수주 css파일 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/shipping/shippingList.jsp
=> [2023.04.12]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/customer/customerList.jsp
[2023.04.12] QR코드 잘림방지를 위한 거래처디테일 팝업사이즈 수정
=> [2023.04.12] QR코드 잘림방지를 위한 거래처디테일 팝업사이즈 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/content.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractList.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/contractWrite.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findContract.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findName.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findName2.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findProduct.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/update.jsp
=> [2023.04.12] 수주관리 메뉴 파비콘 추가

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findContract.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findName.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findName2.jsp, Mealki.s_Fridge/src/main/webapp/WEB-INF/views/business/contract/findProduct.jsp
=> [2023.04.12] 수주관리메뉴 관련 팝업 제목 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/main/top.jsp
=> [2023.04.12] main- top 미사용 메뉴 삭제

Mealki.s_Fridge/src/main/resources/mappers/shippingMapper.xml, Mealki.s_Fridge/target/classes/mappers/shippingMapper.xml
출하신규등록시 생산량=수주량(같은수량)만 리스트나오게 sql구문수정
=> [2023.04.13]

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/unstore/insertUnstore.jsp
=> [2023.04.13] 시연을 위한 권한 조정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp
=> [2023.04.13] 입고 오류 수정

Mealki.s_Fridge/src/main/webapp/WEB-INF/views/wms/store/insertStore.jsp
=> [2023.04.13] 입고 오류 수정..
